services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: embedder-backend
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      - PORT=8888
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001,http://localhost:3333
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/embedder}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME:-embedder}
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=${KEYCLOAK_REALM:-embedder}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID:-embedder-client}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_ADMIN_CLIENT_ID=${KEYCLOAK_ADMIN_CLIENT_ID:-admin-cli}
      - KEYCLOAK_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USERNAME:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
    depends_on:
      - mongodb
      - keycloak
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: embedder-frontend
    ports:
      - "3333:3333"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - PORT=3333
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://localhost:8888
    depends_on:
      - backend
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    container_name: embedder-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=embedder
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: embedder-keycloak
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: embedder-postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  mongodb_data:
  postgres_data:
  backend_node_modules:
  frontend_node_modules:
