name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  version-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Read current version
      id: version
      run: |
        if [ -f VERSION ]; then
          echo "current_version=$(cat VERSION)" >> $GITHUB_OUTPUT
        else
          echo "current_version=0.0.0" >> $GITHUB_OUTPUT
        fi
      
    - name: Calculate new version
      id: new_version
      if: github.event_name == 'push'
      run: |
        current_version="${{ steps.version.outputs.current_version }}"
        IFS='.' read -r major minor patch <<< "$current_version"
        new_patch=$((patch + 1))
        new_version="${major}.${minor}.${new_patch}"
        echo "new_version=${new_version}" >> $GITHUB_OUTPUT
        echo "New version: ${new_version}"
      
    - name: Update VERSION file
      if: github.event_name == 'push'
      run: |
        echo "${{ steps.new_version.outputs.new_version }}" > VERSION
        echo "Updated VERSION file to ${{ steps.new_version.outputs.new_version }}"
      
    - name: Commit and push version update
      if: github.event_name == 'push'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add VERSION
        git commit -m "Bump version to ${{ steps.new_version.outputs.new_version }}"
        git push
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME}}
        password: ${{ secrets.DOCKERHUB_PASSWORD}}
        
    - name: Build and push Backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: ${{ github.event_name == 'push' }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME}}/ai-app-backend:latest
          ${{ secrets.DOCKERHUB_USERNAME}}/ai-app-backend:${{ github.event_name == 'push' && steps.new_version.outputs.new_version || steps.version.outputs.current_version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Build and push Frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: ${{ github.event_name == 'push' }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME}}/ai-app-frontend:latest
          ${{ secrets.DOCKERHUB_USERNAME}}/ai-app-frontend:${{ github.event_name == 'push' && steps.new_version.outputs.new_version || steps.version.outputs.current_version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
